import { SoundConfig, SoundId, AudioChannel } from "./audio-types";

export const SOUNDS: Record<SoundId, SoundConfig> = {
  ambient: {
    id: "ambient",
    path: "/audio/ambient.mp3",
    channel: "Ambience",
    defaultVolume: 0.2,
    loop: true,
  },
  "button-click": {
    id: "button-click",
    path: "/audio/button-click.mp3",
    channel: "UI",
    defaultVolume: 0.25,
  },
  "card-hover": {
    id: "card-hover",
    path: "/audio/card-hover.mp3",
    channel: "Cursor",
    defaultVolume: 0.08,
  },
  click: {
    id: "click",
    path: "/audio/click.mp3",
    channel: "Cursor",
    defaultVolume: 0.15,
  },
  close: {
    id: "close",
    path: "/audio/close.mp3",
    channel: "UI",
    defaultVolume: 0.2,
  },
  countdown: {
    id: "countdown",
    path: "/audio/countdown.mp3",
    channel: "Loader",
    defaultVolume: 0.3,
  },
  crowd: {
    id: "crowd",
    path: "/audio/crowd.mp3",
    channel: "Ambience",
    defaultVolume: 0.1,
    loop: true,
  },
  "electric-hum": {
    id: "electric-hum",
    path: "/audio/electric-hum.mp3",
    channel: "Loader",
    defaultVolume: 0.12,
    loop: true,
  },
  "engine-start": {
    id: "engine-start",
    path: "/audio/engine-start.mp3",
    channel: "Loader",
    defaultVolume: 0.35,
  },
  error: {
    id: "error",
    path: "/audio/error.mp3",
    channel: "UI",
    defaultVolume: 0.2,
  },
  "f1-intro": {
    id: "f1-intro",
    path: "/audio/f1-intro.mp3",
    channel: "Ambience",
    defaultVolume: 0.18,
    loop: true,
  },
  "f1-notification": {
    id: "f1-notification",
    path: "/audio/f1-notification.mp3",
    channel: "UI",
    defaultVolume: 0.2,
  },
  hover: {
    id: "hover",
    path: "/audio/hover.mp3",
    channel: "Cursor",
    defaultVolume: 0.08,
  },
  hydraulics: {
    id: "hydraulics",
    path: "/audio/hydraulics.mp3",
    channel: "Garage",
    defaultVolume: 0.25,
  },
  idle: {
    id: "idle",
    path: "/audio/idle.wav",
    channel: "Garage",
    defaultVolume: 0.12,
    loop: true,
  },
  "lap-complete": {
    id: "lap-complete",
    path: "/audio/lap-complete.mp3",
    channel: "UI",
    defaultVolume: 0.25,
  },
  "led-click": {
    id: "led-click",
    path: "/audio/led-click.mp3",
    channel: "Loader",
    defaultVolume: 0.25,
  },
  navigation: {
    id: "navigation",
    path: "/audio/navigation.mp3",
    channel: "UI",
    defaultVolume: 0.2,
  },
  open: {
    id: "open",
    path: "/audio/open.mp3",
    channel: "UI",
    defaultVolume: 0.2,
  },
  "page-transition": {
    id: "page-transition",
    path: "/audio/page-transition.mp3",
    channel: "UI",
    defaultVolume: 0.25,
  },
  rain: {
    id: "rain",
    path: "/audio/rain.mp3",
    channel: "Ambience",
    defaultVolume: 0.12,
    loop: true,
  },
  rev: {
    id: "rev",
    path: "/audio/rev.wav",
    channel: "Garage",
    defaultVolume: 0.2,
  },
  sting: {
    id: "sting",
    path: "/audio/sting.mp3",
    channel: "Loader",
    defaultVolume: 0.25,
  },
  success: {
    id: "success",
    path: "/audio/success.mp3",
    channel: "UI",
    defaultVolume: 0.2,
  },
  ventilation: {
    id: "ventilation",
    path: "/audio/ventilation.mp3",
    channel: "Ambience",
    defaultVolume: 0.08,
    loop: true,
  },
  wind: {
    id: "wind",
    path: "/audio/wind.mp3",
    channel: "Ambience",
    defaultVolume: 0.1,
    loop: true,
  },
};

export const CHANNEL_VOLUMES: Record<AudioChannel, number> = {
  Master: 0.8,
  UI: 0.45,
  Loader: 0.5,
  Garage: 0.45,
  Cursor: 0.3,
  Ambience: 0.35,
  Future: 0.8,
  PitWall: 0.8,
  Telemetry: 0.8,
  Radio: 0.8,
};
