import type { Circuit } from "@/types/circuit";

export const circuits: Circuit[] = [
  {
    id: "bahrain",
    slug: "bahrain-grand-prix",
    name: "Bahrain International Circuit",
    country: "Bahrain",
    flag: "🇧🇭",
    location: "Sakhir",
    length: "5.412 km",
    laps: 57,
    raceDistance: "308.238 km",
    firstGrandPrix: 2004,
    lapRecord: "1:31.447",
    corners: 15,
    drsZones: 3,
    image: "/circuits/hero/monza.png",
    description:
      "A modern desert circuit famous for dramatic night races, heavy braking zones, and multiple overtaking opportunities."
  },
  {
    id: "jeddah",
    slug: "saudi-arabian-grand-prix",
    name: "Jeddah Corniche Circuit",
    country: "Saudi Arabia",
    flag: "🇸🇦",
    location: "Jeddah",
    length: "6.174 km",
    laps: 50,
    raceDistance: "308.450 km",
    firstGrandPrix: 2021,
    lapRecord: "1:30.734",
    corners: 27,
    drsZones: 3,
    image: "/circuits/hero/monza.png",
    description:
      "One of Formula One's fastest street circuits featuring sweeping high-speed corners along the Red Sea coastline."
  },
  {
    id: "melbourne",
    slug: "australian-grand-prix",
    name: "Albert Park Circuit",
    country: "Australia",
    flag: "🇦🇺",
    location: "Melbourne",
    length: "5.278 km",
    laps: 58,
    raceDistance: "306.124 km",
    firstGrandPrix: 1996,
    lapRecord: "1:19.813",
    corners: 14,
    drsZones: 4,
    image: "/circuits/hero/monza.png",
    description:
      "A fast semi-street circuit around Albert Park combining flowing corners with heavy braking zones."
  },
  {
    id: "suzuka",
    slug: "japanese-grand-prix",
    name: "Suzuka Circuit",
    country: "Japan",
    flag: "🇯🇵",
    location: "Suzuka",
    length: "5.807 km",
    laps: 53,
    raceDistance: "307.471 km",
    firstGrandPrix: 1987,
    lapRecord: "1:30.983",
    corners: 18,
    drsZones: 1,
    image: "/circuits/hero/monza.png",
    description:
      "An iconic figure-eight layout loved by drivers for its flowing Esses, Degner curves, and the legendary 130R."
  },
  {
    id: "shanghai",
    slug: "chinese-grand-prix",
    name: "Shanghai International Circuit",
    country: "China",
    flag: "🇨🇳",
    location: "Shanghai",
    length: "5.451 km",
    laps: 56,
    raceDistance: "305.066 km",
    firstGrandPrix: 2004,
    lapRecord: "1:32.238",
    corners: 16,
    drsZones: 2,
    image: "/circuits/hero/monza.png",
    description:
      "A technical Hermann Tilke design featuring one of Formula One's longest back straights and a challenging opening sector."
  },
  {
    id: "miami",
    slug: "miami-grand-prix",
    name: "Miami International Autodrome",
    country: "United States",
    flag: "🇺🇸",
    location: "Miami",
    length: "5.412 km",
    laps: 57,
    raceDistance: "308.326 km",
    firstGrandPrix: 2022,
    lapRecord: "1:29.708",
    corners: 19,
    drsZones: 3,
    image: "/circuits/hero/monza.png",
    description:
      "A modern stadium circuit combining long straights, technical chicanes, and overtaking opportunities."
  },
    {
    id: "imola",
    slug: "emilia-romagna-grand-prix",
    name: "Autodromo Internazionale Enzo e Dino Ferrari",
    country: "Italy",
    flag: "🇮🇹",
    location: "Imola",
    length: "4.909 km",
    laps: 63,
    raceDistance: "309.049 km",
    firstGrandPrix: 1980,
    lapRecord: "1:15.484",
    corners: 19,
    drsZones: 1,
    image: "/circuits/hero/monza.png",
    description:
      "A historic anti-clockwise circuit featuring iconic corners such as Tamburello, Acque Minerali, and Rivazza."
  },
  {
    id: "monaco",
    slug: "monaco-grand-prix",
    name: "Circuit de Monaco",
    country: "Monaco",
    flag: "🇲🇨",
    location: "Monte Carlo",
    length: "3.337 km",
    laps: 78,
    raceDistance: "260.286 km",
    firstGrandPrix: 1950,
    lapRecord: "1:12.909",
    corners: 19,
    drsZones: 1,
    image: "/circuits/hero/monaco.png",
    description:
      "Formula One's most prestigious street circuit where precision, confidence, and qualifying pace are everything."
  },
  {
    id: "montreal",
    slug: "canadian-grand-prix",
    name: "Circuit Gilles Villeneuve",
    country: "Canada",
    flag: "🇨🇦",
    location: "Montreal",
    length: "4.361 km",
    laps: 70,
    raceDistance: "305.270 km",
    firstGrandPrix: 1978,
    lapRecord: "1:13.078",
    corners: 14,
    drsZones: 3,
    image: "/circuits/hero/monza.png",
    description:
      "A fan-favorite circuit featuring long straights, heavy braking zones, and the legendary Wall of Champions."
  },
  {
    id: "silverstone",
    slug: "british-grand-prix",
    name: "Silverstone Circuit",
    country: "United Kingdom",
    flag: "🇬🇧",
    location: "Silverstone",
    length: "5.891 km",
    laps: 52,
    raceDistance: "306.198 km",
    firstGrandPrix: 1950,
    lapRecord: "1:27.097",
    corners: 18,
    drsZones: 2,
    image: "/circuits/hero/silverstone.png",
    description:
      "The birthplace of Formula One, renowned for ultra-fast corners including Maggotts, Becketts, and Copse."
  },
  {
    id: "spa",
    slug: "belgian-grand-prix",
    name: "Circuit de Spa-Francorchamps",
    country: "Belgium",
    flag: "🇧🇪",
    location: "Spa",
    length: "7.004 km",
    laps: 44,
    raceDistance: "308.052 km",
    firstGrandPrix: 1950,
    lapRecord: "1:46.286",
    corners: 19,
    drsZones: 2,
    image: "/circuits/hero/spa.png",
    description:
      "One of Formula One's greatest circuits, famous for Eau Rouge, Raidillon, changing weather, and high-speed racing."
  },
  {
    id: "hungaroring",
    slug: "hungarian-grand-prix",
    name: "Hungaroring",
    country: "Hungary",
    flag: "🇭🇺",
    location: "Budapest",
    length: "4.381 km",
    laps: 70,
    raceDistance: "306.630 km",
    firstGrandPrix: 1986,
    lapRecord: "1:16.627",
    corners: 14,
    drsZones: 2,
    image: "/circuits/hero/monza.png",
    description:
      "A technical and twisty circuit often compared to a kart track where rhythm and tire management are crucial."
  },
    {
    id: "zandvoort",
    slug: "dutch-grand-prix",
    name: "Circuit Zandvoort",
    country: "Netherlands",
    flag: "🇳🇱",
    location: "Zandvoort",
    length: "4.259 km",
    laps: 72,
    raceDistance: "306.587 km",
    firstGrandPrix: 1952,
    lapRecord: "1:11.097",
    corners: 14,
    drsZones: 2,
    image: "/circuits/hero/monza.png",
    description:
      "A flowing seaside circuit featuring dramatic banking, fast corners, and passionate Formula One fans."
  },
  {
    id: "monza",
    slug: "italian-grand-prix",
    name: "Autodromo Nazionale Monza",
    country: "Italy",
    flag: "🇮🇹",
    location: "Monza",
    length: "5.793 km",
    laps: 53,
    raceDistance: "306.720 km",
    firstGrandPrix: 1950,
    lapRecord: "1:21.046",
    corners: 11,
    drsZones: 2,
    image: "/circuits/hero/monza.png",
    description:
      "The Temple of Speed is Formula One's fastest circuit, famous for long straights, heavy braking zones, and passionate Tifosi."
  },
  {
    id: "baku",
    slug: "azerbaijan-grand-prix",
    name: "Baku City Circuit",
    country: "Azerbaijan",
    flag: "🇦🇿",
    location: "Baku",
    length: "6.003 km",
    laps: 51,
    raceDistance: "306.049 km",
    firstGrandPrix: 2016,
    lapRecord: "1:43.009",
    corners: 20,
    drsZones: 2,
    image: "/circuits/hero/monza.png",
    description:
      "A unique street circuit combining ultra-fast straights with the famously narrow castle section."
  },
  {
    id: "marina-bay",
    slug: "singapore-grand-prix",
    name: "Marina Bay Street Circuit",
    country: "Singapore",
    flag: "🇸🇬",
    location: "Singapore",
    length: "4.940 km",
    laps: 62,
    raceDistance: "306.143 km",
    firstGrandPrix: 2008,
    lapRecord: "1:35.867",
    corners: 19,
    drsZones: 4,
    image: "/circuits/hero/monza.png",
    description:
      "Formula One's original night race featuring humid conditions, unforgiving barriers, and a demanding street layout."
  },
  {
    id: "cota",
    slug: "united-states-grand-prix",
    name: "Circuit of the Americas",
    country: "United States",
    flag: "🇺🇸",
    location: "Austin",
    length: "5.513 km",
    laps: 56,
    raceDistance: "308.405 km",
    firstGrandPrix: 2012,
    lapRecord: "1:36.169",
    corners: 20,
    drsZones: 2,
    image: "/circuits/hero/monza.png",
    description:
      "A modern circuit inspired by iconic corners from legendary Formula One venues around the world."
  },
  {
    id: "mexico-city",
    slug: "mexico-city-grand-prix",
    name: "Autódromo Hermanos Rodríguez",
    country: "Mexico",
    flag: "🇲🇽",
    location: "Mexico City",
    length: "4.304 km",
    laps: 71,
    raceDistance: "305.354 km",
    firstGrandPrix: 1963,
    lapRecord: "1:17.774",
    corners: 17,
    drsZones: 3,
    image: "/circuits/hero/monza.png",
    description:
      "A high-altitude circuit known for its massive stadium section, long straight, and reduced aerodynamic drag."
  },  {
    id: "interlagos",
    slug: "sao-paulo-grand-prix",
    name: "Autódromo José Carlos Pace",
    country: "Brazil",
    flag: "🇧🇷",
    location: "São Paulo",
    length: "4.309 km",
    laps: 71,
    raceDistance: "305.879 km",
    firstGrandPrix: 1973,
    lapRecord: "1:10.540",
    corners: 15,
    drsZones: 2,
    image: "/circuits/hero/monza.png",
    description:
      "One of Formula One's most iconic circuits, featuring elevation changes, passionate fans, and unforgettable championship finales."
  },
  {
    id: "las-vegas",
    slug: "las-vegas-grand-prix",
    name: "Las Vegas Strip Circuit",
    country: "United States",
    flag: "🇺🇸",
    location: "Las Vegas",
    length: "6.201 km",
    laps: 50,
    raceDistance: "310.050 km",
    firstGrandPrix: 2023,
    lapRecord: "1:35.490",
    corners: 17,
    drsZones: 2,
    image: "/circuits/hero/las-vegas.png",
    description:
      "A spectacular night race through the Las Vegas Strip featuring long straights, heavy braking zones, and dazzling city lights."
  },
  {
    id: "lusail",
    slug: "qatar-grand-prix",
    name: "Lusail International Circuit",
    country: "Qatar",
    flag: "🇶🇦",
    location: "Lusail",
    length: "5.419 km",
    laps: 57,
    raceDistance: "308.611 km",
    firstGrandPrix: 2021,
    lapRecord: "1:24.319",
    corners: 16,
    drsZones: 2,
    image: "/circuits/hero/monza.png",
    description:
      "A fast-flowing circuit under floodlights that rewards confidence through medium- and high-speed corners."
  },
  {
    id: "yas-marina",
    slug: "abu-dhabi-grand-prix",
    name: "Yas Marina Circuit",
    country: "United Arab Emirates",
    flag: "🇦🇪",
    location: "Abu Dhabi",
    length: "5.281 km",
    laps: 58,
    raceDistance: "306.183 km",
    firstGrandPrix: 2009,
    lapRecord: "1:26.103",
    corners: 16,
    drsZones: 2,
    image: "/circuits/hero/monza.png",
    description:
      "The traditional Formula One season finale featuring a modern layout, marina backdrop, and sunset-to-night racing."
  },
  {
    id: "red-bull-ring",
    slug: "austrian-grand-prix",
    name: "Red Bull Ring",
    country: "Austria",
    flag: "🇦🇹",
    location: "Spielberg",
    length: "4.318 km",
    laps: 71,
    raceDistance: "306.452 km",
    firstGrandPrix: 1970,
    lapRecord: "1:05.619",
    corners: 10,
    drsZones: 3,
    image: "/circuits/hero/monza.png",
    description:
      "A short but action-packed circuit nestled in the Styrian mountains, known for steep elevation changes and overtaking."
  },
  {
    id: "catalunya",
    slug: "spanish-grand-prix",
    name: "Circuit de Barcelona-Catalunya",
    country: "Spain",
    flag: "🇪🇸",
    location: "Barcelona",
    length: "4.657 km",
    laps: 66,
    raceDistance: "307.236 km",
    firstGrandPrix: 1991,
    lapRecord: "1:16.330",
    corners: 14,
    drsZones: 2,
    image: "/circuits/hero/monza.png",
    description:
      "A balanced circuit combining long corners, technical sections, and a main straight that has long been used for Formula One testing."
  },
  {
    id: "hockenheim",
    slug: "german-grand-prix",
    name: "Hockenheimring",
    country: "Germany",
    flag: "🇩🇪",
    location: "Hockenheim",
    length: "4.574 km",
    laps: 67,
    raceDistance: "306.458 km",
    firstGrandPrix: 1970,
    lapRecord: "1:13.780",
    corners: 17,
    drsZones: 2,
    image: "/circuits/hero/monza.png",
    description:
      "A fast track through the Baden-Württemberg forests, combining high-speed straights with a tight, amphitheater-like stadium section."
  }
];

export const featuredCircuit: Circuit = circuits.find(
  (circuit) => circuit.id === "monza",
) ?? circuits[0];