// lib/drivers.ts
import type { Driver } from "@/types/driver";

export const drivers: Driver[] = [
  {
    id: "max-verstappen",
    slug: "max-verstappen",
    name: "Max Verstappen",
    number: 1,
    team: "Red Bull Racing",
    country: "Netherlands",
    flag: "🇳🇱",
    image: "/images/drivers/max-verstappen.png",
    teamColor: "#3671C6",
    points: 410,
    wins: 11,
    podiums: 15,
  },
  {
    id: "lando-norris",
    slug: "lando-norris",
    name: "Lando Norris",
    number: 4,
    team: "McLaren",
    country: "United Kingdom",
    flag: "🇬🇧",
    image: "/images/drivers/lando-norris.png",
    teamColor: "#FF8000",
    points: 372,
    wins: 8,
    podiums: 14,
  },
  {
    id: "charles-leclerc",
    slug: "charles-leclerc",
    name: "Charles Leclerc",
    number: 16,
    team: "Ferrari",
    country: "Monaco",
    flag: "🇲🇨",
    image: "/images/drivers/charles-leclerc.png",
    teamColor: "#DC0000",
    points: 356,
    wins: 8,
    podiums: 13,
  },
  {
    id: "oscar-piastri",
    slug: "oscar-piastri",
    name: "Oscar Piastri",
    number: 81,
    team: "McLaren",
    country: "Australia",
    flag: "🇦🇺",
    image: "/images/drivers/oscar-piastri.png",
    teamColor: "#FF8000",
    points: 338,
    wins: 8,
    podiums: 12,
  },
  {
    id: "lewis-hamilton",
    slug: "lewis-hamilton",
    name: "Lewis Hamilton",
    number: 44,
    team: "Ferrari",
    country: "United Kingdom",
    flag: "🇬🇧",
    image: "/images/drivers/lewis-hamilton.png",
    teamColor: "#DC0000",
    points: 282,
    wins: 105,
    podiums: 202,
  },
  {
    id: "george-russell",
    slug: "george-russell",
    name: "George Russell",
    number: 63,
    team: "Mercedes",
    country: "United Kingdom",
    flag: "🇬🇧",
    image: "/images/drivers/george-russell.png",
    teamColor: "#27F4D2",
    points: 265,
    wins: 3,
    podiums: 18,
  },
  {
    id: "fernando-alonso",
    slug: "fernando-alonso",
    name: "Fernando Alonso",
    number: 14,
    team: "Aston Martin",
    country: "Spain",
    flag: "🇪🇸",
    image: "/images/drivers/fernando-alonso.png",
    teamColor: "#006F62",
    points: 198,
    wins: 32,
    podiums: 106,
  },
  {
    id: "carlos-sainz",
    slug: "carlos-sainz",
    name: "Carlos Sainz",
    number: 55,
    team: "Williams",
    country: "Spain",
    flag: "🇪🇸",
    image: "/images/drivers/carlos-sainz.png",
    teamColor: "#005AFF",
    points: 176,
    wins: 4,
    podiums: 28,
  },
  {
    id: "kimi-antonelli",
    slug: "kimi-antonelli",
    name: "Andrea Kimi Antonelli",
    number: 12,
    team: "Mercedes",
    country: "Italy",
    flag: "🇮🇹",
    image: "/images/drivers/kimi-antonelli.png",
    teamColor: "#27F4D2",
    points: 154,
    wins: 0,
    podiums: 2,
  },
  {
    id: "alexander-albon",
    slug: "alexander-albon",
    name: "Alexander Albon",
    number: 23,
    team: "Williams",
    country: "Thailand",
    flag: "🇹🇭",
    image: "/images/drivers/alexander-albon.png",
    teamColor: "#005AFF",
    points: 128,
    wins: 0,
    podiums: 2,
  },
  {
    id: "pierre-gasly",
    slug: "pierre-gasly",
    name: "Pierre Gasly",
    number: 10,
    team: "Alpine",
    country: "France",
    flag: "🇫🇷",
    image: "/images/drivers/pierre-gasly.png",
    teamColor: "#0090FF",
    points: 116,
    wins: 1,
    podiums: 5,
  },
  {
    id: "esteban-ocon",
    slug: "esteban-ocon",
    name: "Esteban Ocon",
    number: 31,
    team: "Haas",
    country: "France",
    flag: "🇫🇷",
    image: "/images/drivers/esteban-ocon.png",
    teamColor: "#B6BABD",
    points: 101,
    wins: 1,
    podiums: 4,
  },
  {
    id: "nico-hulkenberg",
    slug: "nico-hulkenberg",
    name: "Nico Hülkenberg",
    number: 27,
    team: "Kick Sauber",
    country: "Germany",
    flag: "🇩🇪",
    image: "/images/drivers/nico-hulkenberg.png",
    teamColor: "#52E252",
    points: 86,
    wins: 0,
    podiums: 0,
  },
  {
    id: "gabriel-bortoleto",
    slug: "gabriel-bortoleto",
    name: "Gabriel Bortoleto",
    number: 5,
    team: "Kick Sauber",
    country: "Brazil",
    flag: "🇧🇷",
    image: "/images/drivers/gabriel-bortoleto.png",
    teamColor: "#52E252",
    points: 74,
    wins: 0,
    podiums: 1,
  },
  {
    id: "yuki-tsunoda",
    slug: "yuki-tsunoda",
    name: "Yuki Tsunoda",
    number: 22,
    team: "Red Bull Racing",
    country: "Japan",
    flag: "🇯🇵",
    image: "/images/drivers/yuki-tsunoda.png",
    teamColor: "#3671C6",
    points: 68,
    wins: 0,
    podiums: 0,
  },
  {
    id: "isack-hadjar",
    slug: "isack-hadjar",
    name: "Isack Hadjar",
    number: 6,
    team: "Racing Bulls",
    country: "France",
    flag: "🇫🇷",
    image: "/images/drivers/isack-hadjar.png",
    teamColor: "#6692FF",
    points: 61,
    wins: 0,
    podiums: 0,
  },
  {
    id: "liam-lawson",
    slug: "liam-lawson",
    name: "Liam Lawson",
    number: 30,
    team: "Racing Bulls",
    country: "New Zealand",
    flag: "🇳🇿",
    image: "/images/drivers/liam-lawson.png",
    teamColor: "#6692FF",
    points: 54,
    wins: 0,
    podiums: 0,
  },
  {
    id: "lance-stroll",
    slug: "lance-stroll",
    name: "Lance Stroll",
    number: 18,
    team: "Aston Martin",
    country: "Canada",
    flag: "🇨🇦",
    image: "/images/drivers/lance-stroll.png",
    teamColor: "#006F62",
    points: 47,
    wins: 0,
    podiums: 3,
  },
  {
    id: "oliver-bearman",
    slug: "oliver-bearman",
    name: "Oliver Bearman",
    number: 87,
    team: "Haas",
    country: "United Kingdom",
    flag: "🇬🇧",
    image: "/images/drivers/oliver-bearman.png",
    teamColor: "#B6BABD",
    points: 39,
    wins: 0,
    podiums: 0,
  },
  {
    id: "franco-colapinto",
    slug: "franco-colapinto",
    name: "Franco Colapinto",
    number: 43,
    team: "Alpine",
    country: "Argentina",
    flag: "🇦🇷",
    image: "/images/drivers/franco-colapinto.png",
    teamColor: "#0090FF",
    points: 28,
    wins: 0,
    podiums: 0,
  },
];