import type {
  ConstructorStanding,
  DriverStanding,
  SeasonStats,
} from "@/types/standings";

export const driverStandings: DriverStanding[] = [
  {
    position: 1,
    driverId: "oscar-piastri",
    driverName: "Oscar Piastri",
    team: "McLaren",
    points: 266,
    wins: 6,
    podiums: 10,
    country: "Australia",
    flag: "🇦🇺",
  },
  {
    position: 2,
    driverId: "lando-norris",
    driverName: "Lando Norris",
    team: "McLaren",
    points: 250,
    wins: 5,
    podiums: 11,
    country: "United Kingdom",
    flag: "🇬🇧",
  },
  {
    position: 3,
    driverId: "max-verstappen",
    driverName: "Max Verstappen",
    team: "Red Bull Racing",
    points: 185,
    wins: 2,
    podiums: 7,
    country: "Netherlands",
    flag: "🇳🇱",
  },
  {
    position: 4,
    driverId: "george-russell",
    driverName: "George Russell",
    team: "Mercedes",
    points: 157,
    wins: 1,
    podiums: 5,
    country: "United Kingdom",
    flag: "🇬🇧",
  },
  {
    position: 5,
    driverId: "charles-leclerc",
    driverName: "Charles Leclerc",
    team: "Ferrari",
    points: 139,
    wins: 0,
    podiums: 5,
    country: "Monaco",
    flag: "🇲🇨",
  },
  {
    position: 6,
    driverId: "lewis-hamilton",
    driverName: "Lewis Hamilton",
    team: "Ferrari",
    points: 109,
    wins: 0,
    podiums: 2,
    country: "United Kingdom",
    flag: "🇬🇧",
  },
  {
    position: 7,
    driverId: "kimi-antonelli",
    driverName: "Kimi Antonelli",
    team: "Mercedes",
    points: 63,
    wins: 0,
    podiums: 1,
    country: "Italy",
    flag: "🇮🇹",
  },
  {
    position: 8,
    driverId: "alexander-albon",
    driverName: "Alexander Albon",
    team: "Williams",
    points: 54,
    wins: 0,
    podiums: 0,
    country: "Thailand",
    flag: "🇹🇭",
  },
  {
    position: 9,
    driverId: "nico-hulkenberg",
    driverName: "Nico Hülkenberg",
    team: "Kick Sauber",
    points: 37,
    wins: 0,
    podiums: 1,
    country: "Germany",
    flag: "🇩🇪",
  },
  {
    position: 10,
    driverId: "esteban-ocon",
    driverName: "Esteban Ocon",
    team: "Haas",
    points: 27,
    wins: 0,
    podiums: 0,
    country: "France",
    flag: "🇫🇷",
  },
  {
    position: 11,
    driverId: "pierre-gasly",
    driverName: "Pierre Gasly",
    team: "Alpine",
    points: 23,
    wins: 0,
    podiums: 0,
    country: "France",
    flag: "🇫🇷",
  },
  {
    position: 12,
    driverId: "fernando-alonso",
    driverName: "Fernando Alonso",
    team: "Aston Martin",
    points: 20,
    wins: 0,
    podiums: 0,
    country: "Spain",
    flag: "🇪🇸",
  },
  {
    position: 13,
    driverId: "carlos-sainz",
    driverName: "Carlos Sainz",
    team: "Williams",
    points: 18,
    wins: 0,
    podiums: 0,
    country: "Spain",
    flag: "🇪🇸",
  },
  {
    position: 14,
    driverId: "yuki-tsunoda",
    driverName: "Yuki Tsunoda",
    team: "Red Bull Racing",
    points: 16,
    wins: 0,
    podiums: 0,
    country: "Japan",
    flag: "🇯🇵",
  },
  {
    position: 15,
    driverId: "lance-stroll",
    driverName: "Lance Stroll",
    team: "Aston Martin",
    points: 15,
    wins: 0,
    podiums: 0,
    country: "Canada",
    flag: "🇨🇦",
  },
  {
    position: 16,
    driverId: "isack-hadjar",
    driverName: "Isack Hadjar",
    team: "Racing Bulls",
    points: 14,
    wins: 0,
    podiums: 0,
    country: "France",
    flag: "🇫🇷",
  },
  {
    position: 17,
    driverId: "liam-lawson",
    driverName: "Liam Lawson",
    team: "Racing Bulls",
    points: 12,
    wins: 0,
    podiums: 0,
    country: "New Zealand",
    flag: "🇳🇿",
  },
  {
    position: 18,
    driverId: "oliver-bearman",
    driverName: "Oliver Bearman",
    team: "Haas",
    points: 10,
    wins: 0,
    podiums: 0,
    country: "United Kingdom",
    flag: "🇬🇧",
  },
  {
    position: 19,
    driverId: "gabriel-bortoleto",
    driverName: "Gabriel Bortoleto",
    team: "Kick Sauber",
    points: 8,
    wins: 0,
    podiums: 0,
    country: "Brazil",
    flag: "🇧🇷",
  },
  {
    position: 20,
    driverId: "franco-colapinto",
    driverName: "Franco Colapinto",
    team: "Alpine",
    points: 6,
    wins: 0,
    podiums: 0,
    country: "Argentina",
    flag: "🇦🇷",
  },
];

export const constructorStandings: ConstructorStanding[] = [
  {
    position: 1,
    teamId: "mclaren",
    teamName: "McLaren",
    points: 516,
    wins: 11,
    podiums: 21,
    country: "United Kingdom",
    color: "#FF8700",
  },
  {
    position: 2,
    teamId: "ferrari",
    teamName: "Ferrari",
    points: 248,
    wins: 0,
    podiums: 7,
    country: "Italy",
    color: "#DC0000",
  },
  {
    position: 3,
    teamId: "mercedes",
    teamName: "Mercedes",
    points: 220,
    wins: 1,
    podiums: 6,
    country: "Germany",
    color: "#00D2BE",
  },
  {
    position: 4,
    teamId: "red-bull-racing",
    teamName: "Red Bull Racing",
    points: 201,
    wins: 2,
    podiums: 7,
    country: "Austria",
    color: "#1E41FF",
  },
  {
    position: 5,
    teamId: "williams",
    teamName: "Williams",
    points: 72,
    wins: 0,
    podiums: 0,
    country: "United Kingdom",
    color: "#005AFF",
  },
  {
    position: 6,
    teamId: "kick-sauber",
    teamName: "Kick Sauber",
    points: 45,
    wins: 0,
    podiums: 1,
    country: "Switzerland",
    color: "#52E252",
  },
  {
    position: 7,
    teamId: "haas",
    teamName: "Haas",
    points: 37,
    wins: 0,
    podiums: 0,
    country: "United States",
    color: "#B6BABD",
  },
  {
    position: 8,
    teamId: "aston-martin",
    teamName: "Aston Martin",
    points: 35,
    wins: 0,
    podiums: 0,
    country: "United Kingdom",
    color: "#006F62",
  },
  {
    position: 9,
    teamId: "racing-bulls",
    teamName: "Racing Bulls",
    points: 26,
    wins: 0,
    podiums: 0,
    country: "Italy",
    color: "#233A7A",
  },
  {
    position: 10,
    teamId: "alpine",
    teamName: "Alpine",
    points: 29,
    wins: 0,
    podiums: 0,
    country: "France",
    color: "#0090FF",
  },
];

export const seasonStats: SeasonStats = {
  season: 2025,
  completedRounds: 12,
  totalRounds: 24,
  totalDrivers: 20,
  totalConstructors: 10,
  leader: "Oscar Piastri",
  leadingTeam: "McLaren",
};